
/**
 * APP COMPONENT DOCUMENTATION
 * 
 * V1.7 Update: Cinematic High-Aesthetic Overhaul
 * 
 * Features:
 * - Ultra-Smooth Letter Animation: Fluid sine-wave floating for "LeadReddit".
 * - Liquid Feature Pop-ups: Cards that sink into the black liquid and resurface, 
 *   lighting up with dynamic "fills" (Red/Blue/Glow).
 * - Animated Buttons: Ghost buttons that fill with solid white/glow on hover.
 * - Onboarding Flow: A 3-step immersive guide to the LeadReddit engine.
 * - Unified Theme: The dashboard now shares the dark crimson liquid aesthetic of the landing page.
 */

import React, { useState, useMemo, useEffect, useRef } from 'react';
import { analyzeService, qualifyLeads } from './services/geminiService';
import { getAccessToken, searchReddit } from './services/redditService';
import { LeadCard, LeadCardSkeleton } from './components/LeadCard';
import { AppState, TimeFilter } from './types';

const FeaturePopup: React.FC<{
  text: string;
  icon: React.ReactNode;
  delay: string;
  pos: string;
  fillColor: string;
}> = ({ text, icon, delay, pos, fillColor }) => (
  <div
    className={`absolute ${pos} flex flex-col items-center justify-center p-4 animate-sink-rise pointer-events-none group`}
    style={{ animationDelay: delay }}
  >
    <div className="relative bg-black/40 backdrop-blur-xl border border-white/10 rounded-2xl p-4 shadow-2xl overflow-hidden min-w-[140px]">
      <div className="flex items-center space-x-3 mb-2">
        <div className="text-white/60">{icon}</div>
        <span className="text-[9px] font-black text-white/50 uppercase tracking-widest">{text}</span>
      </div>
      {/* Dynamic Fill Bar */}
      <div className="h-1 w-full bg-white/5 rounded-full overflow-hidden">
        <div
          className={`h-full ${fillColor} animate-fill-progress shadow-[0_0_10px_rgba(255,255,255,0.5)]`}
          style={{ animationDelay: delay }}
        />
      </div>
    </div>
  </div>
);

const Onboarding: React.FC<{ onComplete: () => void }> = ({ onComplete }) => {
  const [step, setStep] = useState(0);
  const steps = [
    {
      title: "The Intelligence Core",
      desc: "Describe your service or paste a URL. Our Gemini Pro engine deconstructs your market niche into surgical search signals.",
      icon: <svg className="w-12 h-12 text-rose-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5" d="M13 10V3L4 14h7v7l9-11h-7z" /></svg>
    },
    {
      title: "Real-time Signal Refinement",
      desc: "Refine keywords and target subreddits manually. Control exactly where our crawlers look for high-intent conversations.",
      icon: <svg className="w-12 h-12 text-blue-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5" d="M12 6V4m0 2a2 2 0 100 4m0-4a2 2 0 110 4m-6 8a2 2 0 100-4m0 4a2 2 0 110-4m0 4v2m0-6V4m6 6v10m6-2a2 2 0 100-4m0 4a2 2 0 110-4m0 4v2m0-6V4" /></svg>
    },
    {
      title: "AI-Qualified Leads",
      desc: "Get list of authors with high buyer intent, complete with personalized outreach drafts generated by Gemini Flash.",
      icon: <svg className="w-12 h-12 text-emerald-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
    }
  ];

  return (
    <div className="fixed inset-0 z-[100] bg-black/90 backdrop-blur-3xl flex items-center justify-center p-6">
      <div className="max-w-md w-full bg-zinc-900 border border-white/10 rounded-[2.5rem] p-10 shadow-2xl animate-fade-in">
        <div className="flex justify-center mb-8">{steps[step].icon}</div>
        <h3 className="text-2xl font-black text-white text-center mb-4 tracking-tight">{steps[step].title}</h3>
        <p className="text-zinc-400 text-center leading-relaxed mb-10 text-sm font-medium">{steps[step].desc}</p>
        <div className="flex items-center justify-between">
          <div className="flex space-x-2">
            {steps.map((_, i) => (
              <div key={i} className={`h-1.5 w-6 rounded-full transition-all duration-500 ${i === step ? 'bg-rose-600 w-10' : 'bg-zinc-800'}`} />
            ))}
          </div>
          <button
            onClick={() => step < steps.length - 1 ? setStep(step + 1) : onComplete()}
            className="bg-white text-black px-8 py-3 rounded-2xl font-black text-xs uppercase tracking-widest hover:scale-105 transition-all"
          >
            {step === steps.length - 1 ? "Initialize" : "Next"}
          </button>
        </div>
      </div>
    </div>
  );
};

const LandingPage: React.FC<{ onStart: () => void }> = ({ onStart }) => {
  const letters = "LeadReddit".split("");

  return (
    <div className="relative min-h-screen w-full bg-black overflow-hidden flex flex-col items-center justify-center font-sans">
      {/* Liquid Background */}
      <div className="absolute inset-0 z-0">
        <div className="absolute top-[-15%] left-[-10%] w-[70%] h-[70%] bg-red-900/40 rounded-full mix-blend-screen filter blur-[140px] animate-liquid-flow" />
        <div className="absolute bottom-[-15%] right-[-10%] w-[70%] h-[70%] bg-rose-950/30 rounded-full mix-blend-screen filter blur-[140px] animate-liquid-flow-reverse" />
        <div className="absolute top-[20%] left-[30%] w-[30%] h-[30%] bg-blue-900/10 rounded-full mix-blend-overlay filter blur-[100px] animate-liquid-flow" />
      </div>

      {/* Sinking/Rising Features */}
      <FeaturePopup
        text="Intelligence Core"
        icon={<svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13 10V3L4 14h7v7l9-11h-7z" /></svg>}
        delay="0s" pos="top-[15%] left-[10%]" fillColor="bg-rose-600"
      />
      <FeaturePopup
        text="Signal Search"
        icon={<svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" /></svg>}
        delay="2s" pos="top-[65%] right-[15%]" fillColor="bg-blue-600"
      />
      <FeaturePopup
        text="Persona Analysis"
        icon={<svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" /></svg>}
        delay="4s" pos="bottom-[15%] left-[20%]" fillColor="bg-amber-600"
      />
      <FeaturePopup
        text="Auto Outreach"
        icon={<svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" /></svg>}
        delay="1s" pos="top-[25%] right-[10%]" fillColor="bg-emerald-600"
      />

      {/* Main Content */}
      <div className="relative z-10 text-center">
        <h1 className="flex justify-center mb-16 select-none">
          {letters.map((char, i) => (
            <span
              key={i}
              className="inline-block text-6xl sm:text-8xl font-black text-white tracking-tighter animate-fluid-text shadow-xl"
              style={{ animationDelay: `${i * 0.1}s` }}
            >
              {char}
            </span>
          ))}
        </h1>

        <div className="flex flex-col sm:flex-row gap-6 justify-center items-center">
          <button
            onClick={onStart}
            className="group relative w-56 h-16 bg-transparent border-2 border-white rounded-full overflow-hidden transition-all duration-500 hover:scale-110 active:scale-95 shadow-2xl"
          >
            <div className="absolute inset-0 bg-white translate-y-full group-hover:translate-y-0 transition-transform duration-500 ease-out" />
            <span className="relative z-10 text-[11px] font-black uppercase tracking-[0.3em] text-white group-hover:text-black transition-colors">Get Started</span>
          </button>

          <button
            onClick={onStart}
            className="group relative w-56 h-16 bg-transparent border-2 border-white/20 rounded-full overflow-hidden transition-all duration-500 hover:scale-110 active:scale-95"
          >
            <div className="absolute inset-0 bg-white/10 translate-y-full group-hover:translate-y-0 transition-transform duration-500 ease-out" />
            <span className="relative z-10 text-[11px] font-black uppercase tracking-[0.3em] text-white/60 group-hover:text-white transition-colors">Sign In</span>
          </button>
        </div>
      </div>


    </div>
  );
};

const App: React.FC = () => {
  const [navState, setNavState] = useState<'landing' | 'onboarding' | 'app'>('landing');
  const [input, setInput] = useState('');
  const [newKeyword, setNewKeyword] = useState('');
  const [newSubreddit, setNewSubreddit] = useState('');
  const [isAddingKeyword, setIsAddingKeyword] = useState(false);
  const [isAddingSubreddit, setIsAddingSubreddit] = useState(false);
  const [isFeedbackOpen, setIsFeedbackOpen] = useState(false);
  const [feedbackText, setFeedbackText] = useState('');
  const [isListening, setIsListening] = useState(false);

  const [isProcessingAudio, setIsProcessingAudio] = useState(false);
  const [transcript, setTranscript] = useState('');

  const recognitionRef = useRef<any>(null);

  const [state, setState] = useState<AppState>({
    analyzing: false,
    scanning: false,
    analysis: null,
    activeKeywords: [],
    activeSubreddits: [],
    leads: [],
    error: null,
    scoreThreshold: 50,
    timeFilter: 'week',
    isDarkMode: true,
  });

  useEffect(() => {
    // Always Dark for the new aesthetic
    document.documentElement.classList.add('dark');
  }, []);

  useEffect(() => {
    const SpeechRecognition = (window as any).SpeechRecognition || (window as any).webkitSpeechRecognition;
    if (SpeechRecognition) {
      recognitionRef.current = new SpeechRecognition();
      recognitionRef.current.continuous = true;
      recognitionRef.current.interimResults = true;

      recognitionRef.current.onresult = (event: any) => {
        let final = '';
        let interim = '';
        for (let i = 0; i < event.results.length; i++) {
          if (event.results[i].isFinal) {
            final += event.results[i][0].transcript;
          } else {
            interim += event.results[i][0].transcript;
          }
        }
        setTranscript(final + interim);
      };

      recognitionRef.current.onend = () => {
        if (isListening) {
          stopListening();
        }
      };

      recognitionRef.current.onerror = (event: any) => {
        console.error("Speech error", event);
        stopListening();
      };
    }
  }, [isListening]); // Re-bind if needed, but ref should be stable.

  const startListening = () => {
    if (!recognitionRef.current) return alert('Speech recognition is not supported.');
    setTranscript('');
    try {
      recognitionRef.current.start();
      setIsListening(true);
    } catch (e) {
      console.error('Speech start error', e);
    }
  };

  const stopListening = async () => {
    if (recognitionRef.current) recognitionRef.current.stop();
    setIsListening(false);

    if (transcript.trim()) {
      setIsProcessingAudio(true);

      try {
        // Call the refinement API
        const response = await fetch('/api/gemini-refine', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ text: transcript })
        });

        if (response.ok) {
          const data = await response.json();
          const refinedText = data.refinedText || transcript; // Fallback to raw if empty

          setInput(prev => {
            const lastChar = prev.slice(-1);
            const separator = (lastChar && lastChar !== ' ') ? ' ' : '';
            return prev + separator + refinedText.trim();
          });
        } else {
          // Fallback if API fails
          console.error("Refinement failed", await response.text());
          setInput(prev => prev + ' ' + transcript);
        }
      } catch (err) {
        console.error("Refinement error", err);
        setInput(prev => prev + ' ' + transcript);
      } finally {
        setTranscript('');
        setIsProcessingAudio(false);
      }
    }
  };

  const toggleListening = () => {
    if (isListening) stopListening();
    else startListening();
  };

  const handleAnalyze = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!input.trim()) return;
    if (isListening) { recognitionRef.current.stop(); setIsListening(false); }

    setState(prev => ({ ...prev, analyzing: true, error: null, leads: [], analysis: null, activeKeywords: [], activeSubreddits: [] }));
    try {
      const analysis = await analyzeService(input);
      setState(prev => ({
        ...prev,
        analysis,
        activeKeywords: analysis.keywords,
        activeSubreddits: analysis.suggestedSubreddits,
        analyzing: false
      }));
    } catch (err) {
      setState(prev => ({ ...prev, error: 'Analysis failed. Please try again.', analyzing: false }));
    }
  };

  const handleScanReddit = async () => {
    if (!state.analysis) return;
    setState(prev => ({ ...prev, scanning: true, error: null, leads: [] }));
    try {
      const token = await getAccessToken();
      const rawLeads = await searchReddit(token, state.activeKeywords, state.activeSubreddits, state.timeFilter);
      if (rawLeads.length === 0) {
        setState(prev => ({ ...prev, error: 'No potential leads found. Try broader keywords.', scanning: false }));
        return;
      }
      const qualifiedLeads = await qualifyLeads(rawLeads, state.analysis);
      setState(prev => ({ ...prev, leads: qualifiedLeads, scanning: false }));
    } catch (err: any) {
      setState(prev => ({ ...prev, error: err.message || 'Failed to scan Reddit.', scanning: false }));
    }
  };

  const addKeyword = () => {
    if (!newKeyword.trim()) return;
    setState(prev => ({ ...prev, activeKeywords: Array.from(new Set([...prev.activeKeywords, newKeyword.trim()])) }));
    setNewKeyword('');
    setIsAddingKeyword(false);
  };

  const removeKeyword = (kw: string) => {
    setState(prev => ({ ...prev, activeKeywords: prev.activeKeywords.filter(k => k !== kw) }));
  };

  const addSubreddit = () => {
    if (!newSubreddit.trim()) return;
    const clean = newSubreddit.trim().replace(/^r\//i, '');
    setState(prev => ({ ...prev, activeSubreddits: Array.from(new Set([...prev.activeSubreddits, clean])) }));
    setNewSubreddit('');
    setIsAddingSubreddit(false);
  };

  const removeSubreddit = (sub: string) => {
    setState(prev => ({ ...prev, activeSubreddits: prev.activeSubreddits.filter(s => s !== sub) }));
  };

  const filteredLeads = useMemo(() => {
    return state.leads.filter(lead => (lead.aiScore || 0) >= state.scoreThreshold);
  }, [state.leads, state.scoreThreshold]);

  if (navState === 'landing') {
    return <LandingPage onStart={() => setNavState('onboarding')} />;
  }

  if (navState === 'onboarding') {
    return <Onboarding onComplete={() => setNavState('app')} />;
  }

  return (
    <div className="min-h-screen bg-black text-white selection:bg-rose-900/40 selection:text-rose-100 font-sans">
      {/* Liquid Background Base */}
      <div className="fixed inset-0 z-0 pointer-events-none opacity-40">
        <div className="absolute top-[-20%] left-[-10%] w-[80%] h-[80%] bg-red-900/20 rounded-full filter blur-[150px] animate-pulse" />
        <div className="absolute bottom-[-20%] right-[-10%] w-[80%] h-[80%] bg-zinc-900 rounded-full filter blur-[150px]" />
      </div>

      {/* Navbar */}
      <header className="relative z-50 bg-black/60 backdrop-blur-3xl border-b border-white/5 sticky top-0 transition-all">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center h-16 sm:h-24">
            <div className="flex items-center space-x-4">
              <div
                className="bg-rose-600 p-2.5 rounded-2xl shadow-[0_0_20px_rgba(225,29,72,0.4)] cursor-pointer hover:scale-110 transition-all"
                onClick={() => setNavState('landing')}
              >
                <svg className="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" d="M13 10V3L4 14h7v7l9-11h-7z" /></svg>
              </div>
              <div>
                <span className="text-xl font-black tracking-tight uppercase">LeadReddit</span>
                <span className="hidden sm:block text-[9px] font-black text-rose-500 uppercase tracking-[0.3em] leading-none mt-1">Intelligence Layer</span>
              </div>
            </div>
            <button onClick={() => setIsFeedbackOpen(true)} className="px-5 py-2 rounded-xl text-[10px] font-black text-white/40 hover:text-white uppercase tracking-widest transition-all">Report Feedback</button>
          </div>
        </div>
      </header>

      <main className="relative z-10 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 sm:py-16 w-full">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 sm:gap-12">

          {/* Left Panel */}
          <div className="lg:col-span-4 space-y-8">
            <div className="bg-zinc-900/50 backdrop-blur-2xl rounded-[3rem] border border-white/5 p-8 sm:p-10 shadow-2xl">
              <div className="flex items-center justify-between mb-8">
                <div className="flex items-center space-x-3">
                  <div className="bg-rose-900/20 p-2 rounded-xl">
                    <svg className="w-5 h-5 text-rose-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M7 8h10M7 12h4m1 8l-4-4H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-3l-4 4z" /></svg>
                  </div>
                  <h2 className="text-[10px] font-black text-zinc-500 uppercase tracking-widest">Offer Context</h2>
                </div>
                <button onClick={toggleListening} className={`p-2 rounded-full transition-all ${isListening ? 'bg-rose-600 text-white animate-pulse' : 'bg-zinc-800 text-zinc-500 hover:text-white'}`}>
                  <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 11a7 7 0 01-7 7m0 0a7 7 0 01-7-7m7 7v4m0 0H8m4 0h4m-4-8a3 3 0 01-3-3V5a3 3 0 116 0v6a3 3 0 01-3 3z" /></svg>
                </button>
              </div>

              <form onSubmit={handleAnalyze} className="space-y-6">
                <textarea
                  value={input}
                  onChange={(e) => setInput(e.target.value)}
                  placeholder={isListening ? 'Listening...' : 'Target URL or Service...'}
                  className="w-full h-36 px-6 py-5 rounded-[2rem] border border-white/5 bg-black/40 text-white focus:ring-4 focus:ring-rose-500/10 focus:border-rose-500/40 outline-none resize-none text-sm transition-all shadow-inner"
                />
                <button
                  disabled={state.analyzing || !input}
                  type="submit"
                  className="group relative w-full h-16 bg-white rounded-[1.5rem] overflow-hidden transition-all duration-300 active:scale-95 disabled:opacity-50"
                >
                  <div className="absolute inset-0 bg-rose-600 translate-y-full group-hover:translate-y-0 transition-transform duration-300" />
                  <div className="relative z-10 flex items-center justify-center space-x-3 text-black group-hover:text-white transition-colors">
                    {state.analyzing ? <div className="animate-spin rounded-full h-4 w-4 border-2 border-current border-t-transparent" /> : <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="3" d="M13 10V3L4 14h7v7l9-11h-7z" /></svg>}
                    <span className="text-[10px] font-black uppercase tracking-widest">{state.analyzing ? 'Deconstructing...' : 'Analyze Market'}</span>
                  </div>
                </button>
              </form>
            </div>

            {state.leads.length > 0 && (
              <div className="bg-zinc-900/50 backdrop-blur-2xl rounded-[3rem] border border-white/5 p-8 sm:p-10 shadow-2xl animate-fade-in">
                <h2 className="text-[10px] font-black text-zinc-500 uppercase tracking-widest mb-6">Discovery Sensitivity</h2>
                <input
                  type="range" min="0" max="100" value={state.scoreThreshold}
                  onChange={(e) => setState(prev => ({ ...prev, scoreThreshold: parseInt(e.target.value) }))}
                  className="w-full h-1 bg-zinc-800 rounded-full appearance-none cursor-pointer accent-rose-600 mb-4"
                />
                <div className="flex justify-between text-[9px] font-black text-zinc-500 tracking-widest">
                  <span className={state.scoreThreshold < 30 ? 'text-rose-500' : ''}>VOLUME</span>
                  <span className="text-white">INTENT: {state.scoreThreshold}%</span>
                  <span className={state.scoreThreshold > 70 ? 'text-rose-500' : ''}>PRECISION</span>
                </div>
              </div>
            )}
          </div>

          {/* Right Panel */}
          <div className="lg:col-span-8 space-y-12">
            {state.analysis ? (
              <div className="bg-zinc-900/50 backdrop-blur-3xl rounded-[3.5rem] border border-white/5 overflow-hidden animate-fade-in shadow-2xl">
                <div className="bg-gradient-to-r from-rose-900/40 to-transparent p-10 sm:p-14 border-b border-white/5">
                  <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-8">
                    <div>
                      <h2 className="text-3xl font-black tracking-tight mb-2">{state.analysis.name}</h2>
                      <div className="flex items-center space-x-2">
                        <div className="w-2 h-2 rounded-full bg-rose-500 animate-pulse" />
                        <span className="text-rose-500 font-black text-[10px] uppercase tracking-widest">Intelligence Live</span>
                      </div>
                    </div>
                    <div className="flex flex-wrap gap-4">
                      <select
                        value={state.timeFilter}
                        onChange={(e) => setState(prev => ({ ...prev, timeFilter: e.target.value as TimeFilter }))}
                        className="bg-black/40 text-white text-[10px] font-black px-5 py-3 rounded-2xl border border-white/5 outline-none uppercase tracking-widest focus:border-rose-500/50"
                      >
                        <option value="hour">Hour</option>
                        <option value="day">Day</option>
                        <option value="week">Week</option>
                        <option value="month">Month</option>
                      </select>
                      <button
                        onClick={handleScanReddit}
                        disabled={state.scanning}
                        className="bg-rose-600 text-white px-10 py-4 rounded-2xl text-[10px] font-black uppercase tracking-widest hover:bg-rose-500 active:scale-95 transition-all disabled:opacity-50 shadow-[0_10px_30px_rgba(225,29,72,0.3)]"
                      >
                        {state.scanning ? 'Scanning...' : 'Fetch Opportunities'}
                      </button>
                    </div>
                  </div>
                </div>

                <div className="p-10 sm:p-14 space-y-12">
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-12">
                    {/* Persona */}
                    <div className="space-y-6">
                      <h3 className="text-[10px] font-black text-zinc-500 uppercase tracking-widest">Strategic Persona</h3>
                      <div className="bg-black/30 p-8 rounded-[2rem] border border-white/5 shadow-inner">
                        <p className="text-zinc-300 text-sm leading-relaxed italic font-medium">"{state.analysis.targetAudience}"</p>
                      </div>
                    </div>

                    {/* Keywords */}
                    <div className="space-y-6">
                      <div className="flex justify-between items-center">
                        <h3 className="text-[10px] font-black text-zinc-500 uppercase tracking-widest">Target Signals</h3>
                        <button onClick={() => setIsAddingKeyword(true)} className="p-2 bg-zinc-800 hover:bg-rose-900/30 text-rose-500 rounded-xl transition-all"><svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="3" d="M12 4v16m8-8H4" /></svg></button>
                      </div>
                      <div className="flex flex-wrap gap-2">
                        {state.activeKeywords.map(kw => (
                          <span key={kw} className="flex items-center space-x-2 text-[10px] font-black bg-white/5 text-zinc-400 px-4 py-2 rounded-xl border border-white/5 hover:border-rose-500/40 transition-all group">
                            <span>{kw.toUpperCase()}</span>
                            <button onClick={() => removeKeyword(kw)} className="opacity-30 group-hover:opacity-100 hover:text-rose-500 transition-opacity">×</button>
                          </span>
                        ))}
                        {isAddingKeyword && (
                          <input autoFocus value={newKeyword} onChange={(e) => setNewKeyword(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && addKeyword()} onBlur={() => !newKeyword && setIsAddingKeyword(false)} className="bg-black/60 text-white text-[10px] font-black px-4 py-2 rounded-xl border border-rose-500/30 outline-none w-32" placeholder="ADD..." />
                        )}
                      </div>
                    </div>
                  </div>

                  {/* Subreddits */}
                  <div className="pt-12 border-t border-white/5 space-y-6">
                    <div className="flex justify-between items-center">
                      <h3 className="text-[10px] font-black text-zinc-500 uppercase tracking-widest">Target Subreddits</h3>
                      <button onClick={() => setIsAddingSubreddit(true)} className="p-2 bg-zinc-800 hover:bg-blue-900/30 text-blue-500 rounded-xl transition-all"><svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="3" d="M12 4v16m8-8H4" /></svg></button>
                    </div>
                    <div className="flex flex-wrap gap-3">
                      {state.activeSubreddits.map(sub => (
                        <span key={sub} className="flex items-center space-x-2 text-[10px] font-black bg-blue-900/10 text-blue-400 px-5 py-2.5 rounded-2xl border border-blue-900/30 hover:border-blue-500 transition-all group">
                          <span className="opacity-40 tracking-widest">R/</span>
                          <span>{sub.toUpperCase()}</span>
                          <button onClick={() => removeSubreddit(sub)} className="opacity-30 group-hover:opacity-100 hover:text-rose-500">×</button>
                        </span>
                      ))}
                      {isAddingSubreddit && (
                        <input autoFocus value={newSubreddit} onChange={(e) => setNewSubreddit(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && addSubreddit()} onBlur={() => !newSubreddit && setIsAddingSubreddit(false)} className="bg-black/60 text-white text-[10px] font-black px-5 py-2.5 rounded-2xl border border-blue-500/30 outline-none w-40" placeholder="R/..." />
                      )}
                    </div>
                  </div>
                </div>
              </div>
            ) : !state.analyzing && (
              <div className="bg-zinc-900/30 border-2 border-dashed border-white/5 rounded-[4rem] p-24 flex flex-col items-center text-center transition-all">
                <div className="w-24 h-24 bg-rose-900/20 rounded-full flex items-center justify-center mb-10 text-rose-500 animate-pulse">
                  <svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5" d="M11 4a2 2 0 114 0v1a2 2 0 11-4 0V4zM4 11a2 2 0 114 0v1a2 2 0 11-4 0v-1zM11 11a2 2 0 114 0v1a2 2 0 11-4 0v-1zM18 11a2 2 0 114 0v1a2 2 0 11-4 0v-1z" /></svg>
                </div>
                <h2 className="text-3xl font-black mb-4 uppercase tracking-tight">Intelligence Standby</h2>
                <p className="text-zinc-500 text-sm max-w-sm leading-relaxed font-medium">Map your audience on the left to begin deep crawlers for intent signals.</p>
              </div>
            )}

            {state.scanning && (
              <div className="space-y-8">
                <div className="bg-zinc-900/50 p-20 rounded-[3rem] border border-white/5 flex flex-col items-center justify-center text-center">
                  <div className="w-14 h-14 border-4 border-rose-900/20 border-t-rose-600 rounded-full animate-spin mb-8 shadow-[0_0_20px_rgba(225,29,72,0.4)]" />
                  <h3 className="text-xl font-black uppercase mb-2">Analyzing Intent</h3>
                  <p className="text-zinc-500 text-sm font-medium">Gemini is evaluating buyer signals in {state.activeSubreddits.length} subreddits...</p>
                </div>
                <LeadCardSkeleton />
                <LeadCardSkeleton />
              </div>
            )}

            {!state.scanning && filteredLeads.length > 0 && (
              <div className="space-y-10 animate-fade-in">
                <div className="flex items-center justify-between px-6">
                  <h2 className="text-2xl font-black uppercase tracking-tight">Verified Opportunities</h2>
                  <div className="bg-emerald-600/20 text-emerald-400 text-[10px] px-6 py-2 rounded-full font-black uppercase tracking-widest border border-emerald-900/40 shadow-xl">{filteredLeads.length} Signals</div>
                </div>
                <div className="grid grid-cols-1 gap-8">
                  {filteredLeads.map((lead) => <LeadCard key={lead.id} lead={lead} />)}
                </div>
              </div>
            )}

            {state.error && !state.scanning && (
              <div className="bg-rose-950/20 border border-rose-900/40 text-rose-400 p-14 rounded-[3rem] text-center space-y-6">
                <svg className="w-12 h-12 mx-auto mb-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" /></svg>
                <h3 className="text-xl font-black uppercase">Search Disruption</h3>
                <p className="text-sm opacity-80 max-w-sm mx-auto">{state.error}</p>
                <button onClick={handleScanReddit} className="bg-rose-600 text-white px-10 py-3 rounded-2xl text-[10px] font-black uppercase tracking-widest shadow-xl">Re-attempt Scan</button>
              </div>
            )}
          </div>
        </div>
      </main>

      {/* Feedback Modal */}
      {isFeedbackOpen && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-6 bg-black/80 backdrop-blur-2xl animate-fade-in">
          <div className="bg-zinc-900 border border-white/10 rounded-[3rem] w-full max-w-md p-12 shadow-2xl">
            <div className="flex justify-between items-center mb-10">
              <h3 className="text-2xl font-black uppercase">System Feedback</h3>
              <button onClick={() => setIsFeedbackOpen(false)} className="text-zinc-500 hover:text-rose-500"><svg className="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="3" d="M6 18L18 6M6 6l12 12" /></svg></button>
            </div>
            <textarea required value={feedbackText} onChange={(e) => setFeedbackText(e.target.value)} placeholder="Tell us how we can improve..." className="w-full h-44 px-6 py-6 rounded-[2rem] bg-black/60 border border-white/5 text-white outline-none focus:border-rose-500/50 transition-all text-sm font-medium mb-8 shadow-inner" />
            <button onClick={() => setIsFeedbackOpen(false)} className="w-full bg-rose-600 py-5 rounded-2xl text-[10px] font-black uppercase tracking-[0.2em] shadow-xl hover:bg-rose-500 transition-all">Submit Protocol</button>
          </div>
        </div>
      )}

      {/* Audio Recording Overlay */}
      {isListening && (
        <div className="fixed inset-0 z-[100] flex flex-col items-center justify-center bg-black/90 backdrop-blur-md animate-fade-in cursor-pointer" onClick={stopListening}>
          <div className="relative">
            <div className="absolute inset-0 bg-rose-500 rounded-full animate-ping opacity-75"></div>
            <div className="relative bg-rose-600 p-8 rounded-full shadow-[0_0_50px_rgba(225,29,72,0.6)]">
              <svg className="w-12 h-12 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 11a7 7 0 01-7 7m0 0a7 7 0 01-7-7m7 7v4m0 0H8m4 0h4m-4-8a3 3 0 01-3-3V5a3 3 0 116 0v6a3 3 0 01-3 3z" /></svg>
            </div>
          </div>
          <h3 className="mt-8 text-2xl font-black uppercase tracking-widest text-white animate-pulse">Listening...</h3>
          <p className="mt-2 text-zinc-400 text-sm font-medium">Tap anywhere to stop</p>
          {transcript && (
            <div className="mt-8 max-w-lg text-center px-6">
              <p className="text-zinc-500 text-xs uppercase tracking-widest mb-2">Live Transcript</p>
              <p className="text-xl text-white font-medium leading-relaxed">"{transcript}"</p>
            </div>
          )}
        </div>
      )}

      {/* Audio Processing Overlay */}
      {isProcessingAudio && (
        <div className="fixed inset-0 z-[100] flex flex-col items-center justify-center bg-black/90 backdrop-blur-md animate-fade-in">
          <div className="w-16 h-16 border-4 border-rose-900/20 border-t-rose-600 rounded-full animate-spin mb-6"></div>
          <h3 className="text-xl font-black uppercase tracking-widest text-white">Processing Audio</h3>
          <p className="mt-2 text-zinc-400 text-sm">Refining your input...</p>
        </div>
      )}

      <footer className="relative z-10 border-t border-white/5 py-20 mt-20 opacity-40">
        <div className="max-w-7xl mx-auto px-4 flex flex-col items-center">
          <p className="text-[9px] font-black uppercase tracking-[0.4em] mb-4">LeadReddit System Core V1.7</p>
          <div className="flex space-x-8 text-[8px] font-black text-zinc-600 uppercase tracking-widest">
            <span>Reddit Discovery Mode</span>
            <span>•</span>
            <span>Gemini Reasoning Neural Layer</span>
            <span>•</span>
            <span>Real-time Crawling</span>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default App;
